### ISSUE TITLE
Please dev help me to solve apex_available issue

### ISSUE THREAD

**Issue by Mikdadali** [syberia-project/official_devices#3]
please help me to solve below issue:

/home/mikdad/syberia/out/soong/.bootstrap/build-globs.ninja -o /home/mikdad/syberia/out/soong/build.ninja Android.bp
error: prebuilts/clang/host/linux-x86/Android.bp:51:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:38:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:41:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:74:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:61:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:64:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:87:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:97:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:84:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:121:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:111:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:108:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:161:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:163:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:171:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:183:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:181:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:191:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:201:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:203:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:211:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:222:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:224:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:232:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:240:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:251:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:262:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:273:28: unrecognized property "native_bridge_supported"
error: prebuilts/clang/host/linux-x86/Android.bp:314:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:297:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:325:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:337:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:349:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:366:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:378:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:390:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:428:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:444:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:461:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:478:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:518:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:510:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:528:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:537:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:547:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:555:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:573:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:565:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:583:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:591:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:601:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:609:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:625:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:644:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:663:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:695:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:706:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:716:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:727:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:737:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:748:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:769:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:758:22: unrecognized property "ramdisk_available"
error: prebuilts/clang/host/linux-x86/Android.bp:786:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:806:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:826:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:846:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:866:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:884:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:902:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:920:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:938:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:958:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:978:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:998:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:1018:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:1036:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:1054:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:1072:19: unrecognized property "apex_available"
error: prebuilts/clang/host/linux-x86/Android.bp:1090:19: unrecognized property "apex_available"
ninja: build stopped: subcommand failed.
11:32:09 soong bootstrap failed with: exit status 1
make: *** [build/make/core/main.mk:21: run_soong_ui] Error 1

Here full logs:
https://del.dog/yfifuckuni

**Comment by mr-hacker-dev** [comment]
these devs are useless af that they don't even pay attention to someone's query and think of them some superiors while they are a pile of garbage who are wasting name of syberia os with their useless work ...

**Comment by blinoff82** [comment]
Outdated
